version: '3'

services:
  producer_consumer_txt:
    container_name: producer_consumer_txt
    build: .
    image: producer_consumer_txt:0.0.1
    command: gunicorn -w 3 -b :8000 -k uvicorn.workers.UvicornWorker -t 90 --preload --max-requests=500 --reload producer_consumer_txt:app
    environment: []
    ports: []
    volumes:
      - ./:/deploy
    depends_on: []
    networks: []

volumes: []

networks: []
